trigger:
  - master

pool:
  name: "ocp-4-agents"

parameters:
  - name: azureRegion
    displayName: Azure region
    type: string
    default: "northeurope"

  - name: networkResourceGroup
    displayName: Network resource group
    type: string
    default: "networking-rg"

  - name: openShiftResourceGroup
    displayName: OpenShift resource group
    type: string
    default: "openshift-1-rg"

  - name: ocpVersion
    displayName: OpenShift version (x.y)
    default: "4.6"

  - name: clusterName
    displayName: Cluster name
    type: string
    default: "devtest"

  - name: baseDomain
    displayName: Base domain
    type: string
    default: "ocp.aerdei.private"

  - name: networkName
    displayName: Network name
    type: string
    default: "ocp-4-vnet"

  - name: controlPlaneSubnet
    displayName: Control plane subnet
    default: "ocp-4-controlplane-subnet"

  - name: computeSubnet
    displayName: Compute node subnet
    default: "ocp-4-compute-subnet"

variables:
  - group: ocp-4-variable-group

steps:
  - task: Bash@3
    displayName: Acquire OpenShift installer
    inputs:
      targetType: "inline"
      script: "curl --location --fail --silent --show-error https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-${{ parameters.ocpVersion }}/openshift-install-linux.tar.gz | tar -xz openshift-install"
      failOnStderr: true

  - task: Bash@3
    displayName: Prepare OpenShift install config file
    inputs:
      targetType: "inline"
      script: |
        mkdir ${{ parameters.clusterName }}
        envsubst < ./installer/install-config.bk.yaml > ./${{ parameters.clusterName }}/install-config.yaml
        cat ./${{ parameters.clusterName }}/install-config.yaml
      failOnStderr: true
    env:
      BASE_DOMAIN: "${{ parameters.baseDomain }}"
      CLUSTER_NAME: "${{ parameters.clusterName }}"
      AZURE_REGION: "${{ parameters.azureRegion }}"
      OCP_RG: "${{ parameters.openShiftResourceGroup }}"
      VNET_RG: "${{ parameters.networkResourceGroup }}"
      VNET_NAME: "${{ parameters.networkName }}"
      CONTROL_PLANE_SUBNET: "${{ parameters.controlPlaneSubnet }}"
      COMPUTE_SUBNET: "${{ parameters.computeSubnet }}"
      PULL_SECRET: $(ocp-4-pullsecret)
      SSH_KEY: $(ocp-4-ssh-pub)

  - task: AzureCLI@2
    displayName: Get subscriptionId
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        subscriptionId=`az account show | jq -r -c .id`
        echo "##vso[task.setvariable variable=subscriptionId;]$subscriptionId"
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: Bash@3
    displayName: Prepare osServicePrincipal.json
    inputs:
      targetType: "inline"
      script: |
        jq --arg key0 'subscriptionId' \
        --arg value0 '$(subscriptionId)' \
        --arg key1 'clientId'   \
        --arg value1 '$(ocp-4-sp-id)' \
        --arg key2 'clientSecret'  \
        --arg value2 '$(ocp-4-sp-pw)' \
        --arg key3 'tenantId' \
        --arg value3 '$(ocp-4-sp-tid)' \
        '. | .[$key0]=$value0 | .[$key1]=$value1 | .[$key2]=$value2 | .[$key3]=$value3' <<< {} | tee osServicePrincipal.json
      failOnStderr: true

  - task: Bash@3
    displayName: Prepare OpenShift manifest files
    inputs:
      targetType: "inline"
      script: |
        ./openshift-install create manifests --dir=./${{ parameters.clusterName }} --log-level error
        rm -f ./${{ parameters.clusterName }}/openshift/99_openshift-cluster-api_master-machines-*.yaml
        sed -i 's/mastersSchedulable: true/mastersSchedulable: false/g' ./${{ parameters.clusterName }}/manifests/cluster-scheduler-02-config.yml
      failOnStderr: true
    env:
      AZURE_AUTH_LOCATION: ./osServicePrincipal.json

  - task: PythonScript@0
    displayName: Add labels to compute machineSet
    inputs:
      scriptSource: inline
      script: |
        #!/usr/bin/env python3
        """This script updates the compute machineset manifests with tags
        found in templates/tags.parameters.json and templates/computetags.json"""
        import glob
        import json
        import yaml
            
        for i in glob.glob(
            "./${{ parameters.clusterName }}/openshift/99_openshift-cluster-api_worker-machineset-*.yaml"
        ):
            with open(i, "r") as f, open(
                "./templates/tags.parameters.json"
            ) as p, open("./templates/computetags.json") as t:
                tagsparams = json.load(p)
                computetags = json.load(t)
                manifest = yaml.safe_load(f)
                manifest["spec"]["template"]["spec"]["providerSpec"]["value"][
                    "tags"
                ] = tagsparams["parameters"]["resourceTags"]["value"]
                manifest["spec"]["template"]["spec"]["providerSpec"]["value"][
                    "tags"
                ].update(computetags)
            with open(i, "w") as f:
                yaml.dump(manifest, f)
              
      pythonInterpreter: /usr/bin/python3
      failOnStderr: true

  - task: Bash@3
    displayName: Get infraId variable
    inputs:
      targetType: "inline"
      script: |
        infraId=`grep -oP "(?<=infrastructureName: ).*" ./${{ parameters.clusterName }}/manifests/cluster-infrastructure-02-config.yml`
        echo "##vso[task.setvariable variable=infraId;]$infraId"
      failOnStderr: true

  - task: Bash@3
    displayName: Create ignition configs
    inputs:
      targetType: "inline"
      script: "./openshift-install create ignition-configs  --dir=./${{ parameters.clusterName }} --log-level error"
      failOnStderr: true

  - task: AzureCLI@2
    displayName: Export credentials to Key Vault
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az keyvault secret set -n "$(infraId)-kubeconfig" --vault-name ocp-4-kv --file ./${{ parameters.clusterName }}/auth/kubeconfig --output none
        az keyvault secret set -n "$(infraId)-kubeadmin-password" --vault-name ocp-4-kv --file ./${{ parameters.clusterName }}/auth/kubeadmin-password --output none
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: AzureCLI@2
    displayName: Deploy identity
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az deployment group create --template-file "./templates/01_identity.json" --parameters baseName='$(infraId)' --parameters networkResourceGroup="${{ parameters.networkResourceGroup }}" -g "${{ parameters.openShiftResourceGroup }}" --parameters @./templates/tags.parameters.json
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: AzureCLI@2
    displayName: Deploy storage
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az deployment group create -g "${{ parameters.openShiftResourceGroup }}" --template-file "./templates/02_storage.json" --parameters baseName='$(infraId)' --parameters @./templates/tags.parameters.json
        storageAccountName=`az deployment group show -g "${{ parameters.openShiftResourceGroup }}" -n 02_storage --query properties.outputs.storageAccountName.value -o tsv`
        storageAccountKey=`az storage account keys list -g ${{ parameters.openShiftResourceGroup }} --account-name $storageAccountName --query "[0].value" -o tsv`
        echo "##vso[task.setvariable variable=storageAccountName;]$storageAccountName"
        echo "##vso[task.setvariable variable=storageAccountKey;]$storageAccountKey"
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: AzureCLI@2
    displayName: Copy VHD to blob container
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        vhdUrl=$(curl -s https://raw.githubusercontent.com/openshift/installer/release-4.6/data/data/rhcos.json | jq -c -r .azure.url)
        az storage blob copy start --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' --destination-blob "rhcos.vhd" --destination-container vhd --source-uri $vhdUrl
        echo "`date -Iseconds`: started blob copy."
        status="unknown"
        while [ "$status" != "success" ]
        do
          status=`az storage blob show --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' --container-name vhd --name "rhcos.vhd" -o tsv --query properties.copy.status`
          echo "`date -Iseconds`: progress is $status."
          sleep 60s
        done
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: AzureCLI@2
    displayName: Upload bootstrap ignition config
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az storage blob upload --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' -c "files" -f "./${{ parameters.clusterName }}/bootstrap.ign" -n "bootstrap.ign"
      addSpnToEnvironment: true

  - task: AzureCLI@2
    displayName: Deploy infrastructure components
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        vhdBlobUrl=`az storage blob url --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' -c vhd -n "rhcos.vhd" -o tsv`
        az deployment group create -g "${{ parameters.openShiftResourceGroup }}" --template-file "./templates/03_infra.json" --parameters privateDNSZoneName="${{ parameters.clusterName }}.${{ parameters.baseDomain }}" --parameters baseName='$(infraId)' --parameters networkResourceGroupName="${{ parameters.networkResourceGroup }}" --parameters virtualNetworkName="${{ parameters.networkName }}" --parameters vhdBlobURL="$vhdBlobUrl" --parameters controlPlaneSubnetName="${{ parameters.controlPlaneSubnet }}" --parameters @./templates/tags.parameters.json
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: AzureCLI@2
    displayName: Deploy bootstrap components
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        bootstrapUrl=`az storage blob url --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' -c "files" -n "bootstrap.ign" -o tsv`
        bootstrapIgnition=`jq -rcnM --arg v "3.1.0" --arg url "$bootstrapUrl" '{ignition:{version:$v,config:{replace:{source:$url}}}}' | base64 -w0`
        az deployment group create -g "${{ parameters.openShiftResourceGroup }}" --template-file "./templates/04_bootstrap.json" --parameters bootstrapIgnition="$bootstrapIgnition" --parameters sshKeyData="$(ocp-4-ssh-pub)" --parameters baseName='$(infraId)' --parameters networkResourceGroupName="${{ parameters.networkResourceGroup }}" --parameters virtualNetworkName="${{ parameters.networkName }}" --parameters controlPlaneSubnetName="${{ parameters.controlPlaneSubnet }}" --parameters @./templates/tags.parameters.json
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: AzureCLI@2
    displayName: Deploy control plane components
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        controlPlaneIgnition=$(base64 -w0 < ./${{ parameters.clusterName }}/master.ign)
        az deployment group create -g "${{ parameters.openShiftResourceGroup }}" --template-file "./templates/05_control_plane.json" --parameters controlPlaneIgnition="$controlPlaneIgnition" --parameters sshKeyData='$(ocp-4-ssh-pub)' --parameters privateDNSZoneName="${{ parameters.clusterName }}.${{ parameters.baseDomain }}" --parameters baseName='$(infraId)' --parameters networkResourceGroupName="${{ parameters.networkResourceGroup }}" --parameters virtualNetworkName="${{ parameters.networkName }}" --parameters controlPlaneSubnetName="${{ parameters.controlPlaneSubnet }}" --parameters @./templates/tags.parameters.json
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: AzureCLI@2
    displayName: Wait for bootstrap-complete and remove bootstrap resources
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        ./openshift-install wait-for bootstrap-complete  --dir=./${{ parameters.clusterName }} --log-level error
        az vm stop -g "${{ parameters.openShiftResourceGroup }}" --name "$(infraId)-bootstrap" --only-show-errors
        az vm deallocate -g "${{ parameters.openShiftResourceGroup }}" --name "$(infraId)-bootstrap" --only-show-errors
        az vm delete -g "${{ parameters.openShiftResourceGroup }}" --name "$(infraId)-bootstrap" --yes --only-show-errors
        az disk delete -g "${{ parameters.openShiftResourceGroup }}" --name "$(infraId)-bootstrap_OSDisk" --no-wait --yes --only-show-errors
        az network nic delete -g "${{ parameters.openShiftResourceGroup }}" --name "$(infraId)-bootstrap-nic" --no-wait --only-show-errors
        az storage blob delete --account-key '$(storageAccountKey)' --account-name '$(storageAccountName)' --container-name files --name bootstrap.ign --only-show-errors
      failOnStandardError: true

  - task: AzureCLI@2
    displayName: Wait for installation to complete
    inputs:
      azureSubscription: "ocp-4-sa-azdo"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        ./openshift-install wait-for install-complete  --dir=./${{ parameters.clusterName }} --log-level error
      failOnStandardError: true
