apiVersion: v1
baseDomain: $BASE_DOMAIN
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    platform:
      azure:
        type: Standard_D4s_v3
        osDisk:
          diskSizeGB: 512
    replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: $CLUSTER_NAME
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 10.4.0.0/14
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  azure:
    region: $AZURE_REGION
    resourceGroupName: $OCP_RG
    outboundType: UserDefinedRouting
    networkResourceGroupName: $VNET_RG
    virtualNetwork: $VNET_NAME
    controlPlaneSubnet: $CONTROL_PLANE_SUBNET
    computeSubnet: $COMPUTE_SUBNET
publish: Internal
credentialsMode: Passthrough
pullSecret: '$PULL_SECRET'
sshKey: '$SSH_KEY'
